version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3-notification-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-"
s3_prefix = "s3-notification-app"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\" EmailSubscription=\"abudusamed@gmail.com\""
image_repositories = []

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "s3-notification-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-"
s3_prefix = "s3-notification-dev"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" EmailSubscription=\"dev-abudusamed@gmail.com\""
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "s3-notification-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-"
s3_prefix = "s3-notification-prod"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\" EmailSubscription=\"prod-abudusamed@gmail.com\""
image_repositories = []