name: Deploy SAM Application

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: verify pom.xml
        run: |
          echo "Current directory: $(pwd)"
          ls -R

      - name: Build with Maven
        run: mvn clean install

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Build application
        run: sam build

      - name: Determine environment
        id: determine-env
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
          else
            echo "env=dev" >> $GITHUB_OUTPUT
          fi

      - name: Deploy SAM application
        run: |
          email_subscription="${{ secrets.EMAIL_SUBSCRIPTION }}"
          environment="${{ steps.determine-env.outputs.env }}"
          
          sam deploy \
            --stack-name s3-notification-$environment \
            --parameter-overrides "Environment=$environment EmailSubscription=$email_subscription" \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset